
[character]
#success_symbol = "[](white)"
#error_symbol = "[](red)"
#vicmd_symbol = "[](green)"

[directory]
style = "blue bold"

[package]
disabled = false

[username]
disabled = false

[hostname]
disabled = false

[aws]
disabled = false

[docker_context]
disabled = true

[git_branch]
disabled = false

[git_commit]
disabled = false

[git_state]
disabled = false

[git_metrics]
disabled = false

[git_status]
disabled = false
